### ISSUE TITLE
ur thing is funnied 

### ISSUE THREAD

**Issue by TerikKek** [Gopro336/Phobos_1.5.4-BUILDABLE-SRC#3]
C:\Users\terik\3D Objects\phobospaste\build\sources\main\java\me\earth\phobos\features\modules\misc\AntiVanish.java:28: error: cannot access AddPlayerData
                for (final SPacketPlayerListItem.AddPlayerData addPlayerData : sPacketPlayerListItem.getEntries()) {
                                                ^
  bad class file: C:\Users\terik\.gradle\caches\minecraft\net\minecraftforge\forge\1.12.2-14.23.5.2847\stable\39\forgeBin-1.12.2-14.23.5.2847.jar(net/minecraft/network/play/server/SPacketPlayerListItem$AddPlayerData.class)
    bad RuntimeInvisibleParameterAnnotations attribute: AddPlayerData(GameProfile,int,GameType,ITextComponent)
    Please remove or make sure it appears in the correct subdirectory of the classpath.

getting this error when building how fix yes?

**Comment by Gopro336** [comment]
gradle setupdecompworkspace
