### ISSUE TITLE
Can someone give me .jar files for versiin 1.8.9 of future client

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [Gopro336/Phobos_1.5.4-BUILDABLE-SRC#7]
@Gopro336 thanks for making it clean but my question is client ia still buggy or it optimised and where you get the codes from.
 Also you are going to work on it or not
 And which program did you use to reverse the obfuscate codes And in this process some codes miss or not.
Kind regards.

**Comment by BLUELIGHTTIGER** [comment]
Also it is possible to use future 1 account on different pc. If yes and if you have future and not using it then shere with others ;) please.

**Comment by MOMIN5** [comment]
what the fuck why would he give you his future account

Also future has hwid lock which is once per pc so you cant use one account on different pcs

**Comment by linustouchtips** [comment]
@BLUELIGHTTIGER  you're retarded

**Comment by BLUELIGHTTIGER** [comment]
I really want to see what kind of hack they give for such big amount of money.
Also asking anyone tried vape cracked by kangroo 
Vape.rip 
And it is safe or virus cau chrome blocking website.

**Comment by BLUELIGHTTIGER** [comment]
@linustouchtips  are you real one who have  12.6 m subs you can give me future client kind regards

**Comment by linustouchtips** [comment]
please shut up

**Comment by BLUELIGHTTIGER** [comment]
@linustouchtips i just need to know you are real ok bro also if your knowlage about computers and java is large enough then please tell me is vape.rip is safe please please.

**Comment by dotheadbro** [comment]
@BLUELIGHTTIGER kiddo its safe, and no its not the real linus, and grow up before you try to do this shit bruh

**Comment by BLUELIGHTTIGER** [comment]
@dotheadbro what you mean kiddo and talk clearly.

**Comment by linustouchtips** [comment]
he's talking fine, your english is so broken lmfao

**Comment by dotheadbro** [comment]
@BLUELIGHTTIGER lmfao im apparently the one not talking clearly

btw vape.rip is legit
